#!/bin/bash
set -e
chown -R mysql:mysql /var/lib/mysql

MYSQL_ROOT_PASSWORD="masterpass12"
MYSQL_DATABASE=${MYSQL_DATABASE:-""}
MYSQL_USER="root"
MYSQL_PASSWORD="masterpass12"
MYSQLD_ARGS=${MYSQLD_ARGS:-""}

tfile=`mktemp`
if [[ ! -f "$tfile" ]]; then
    return 1
fi

cat << EOF > $tfile
USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
CREATE DATABASE IF NOT EXISTS maindb CHARACTER SET utf8 COLLATE utf8_general_ci;
UPDATE user SET password=PASSWORD("$MYSQL_ROOT_PASSWORD") WHERE user='root';
EOF

/usr/sbin/mysqld --bootstrap --verbose=0 $MYSQLD_ARGS < $tfile
rm -f $tfile

exec /usr/sbin/mysqld $MYSQLD_ARGS